participants = summary[[ 
                         'case_id',
                         'sex',
                         'age',
                         'Doing aerobics',
                         'Playing baseball',
                         'Playing basketball',
                         'Biking',
                         'Playing billiards',
                         'Boating',
                         'Bowling',
                         'Climbing, spelunking, caving',
                         'Dancing',
                         'Participating in equestrian sports',
                         'Fishing',
                         'Playing football',
                         'Golfing',
                         'Doing gymnastics',
                         'Hiking',
                         'Playing hockey',
                         'Hunting',
                         'Participating in martial arts',
                         'Playing racquet sports',
                         'Rollerblading',
                         'Running',
                         'Skiing, ice skating, snowboarding',
                         'Playing soccer',
                         'Softball',
                         'Using cardiovascular equipment',
                         'Vehicle touring/racing',
                         'Playing volleyball',
                         'Walking',
                         'Participating in water sports',
                         'Weightlifting/strength training',
                         'Working out, unspecified',
                         'Doing yoga',
                         'Playing sports n.e.c.*','Sports, exercise, & recreation, n.e.c.*']]
