spectators = summary[[
                     'case_id',
                     'sex',
                     'age',
                     'Watching baseball',
                     'Watching basketball',
                     'Watching biking',
                     'Watching billiards',
                     'Watching boating',
                     'Watching equestrian sports',
                     'Watching football',
                     'Watching golfing',
                     'Watching gymnastics',
                     'Watching hockey',
                     'Watching racquet sports',
                     'Watching rodeo competitions',
                     'Watching running',
                     'Watching soccer',
                     'Watching softball',
                     'Watching vehicle touring/racing',
                     'Watching volleyball',
                     'Watching water sports',
                     'Watching people working out, unspecified',
                     'Attending sporting events, n.e.c.*']]
